# Generated by Django 3.2.8 on 2021-11-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20211124_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='description',
            new_name='name',
        ),
    ]
